kind: pipeline
name: default

steps:
- name: build
  image: debian:bullseye-slim
  commands:
  - apt update && apt install -y ca-certificates
  - echo "deb [trusted=yes] https://www.sprintf.io/repos/apt/debian buster main" >> /etc/apt/sources.list && apt update
  - apt install -y cmake g++ git libssl-dev libspdlog-dev nlohmann-json3-dev catch2 libyaml-cpp-dev libcxxopts-dev libpaho-mqtt++-dev stduuid
  - cd $DRONE_WORKSPACE && git submodule update --init
  - mkdir -p build && cd build
  - cmake $DRONE_WORKSPACE
  - make -j4
  - tests/tests
